### ISSUE TITLE
CUDA StreamExecutor conflict

### ISSUE THREAD

**Issue by tkipf** [mdeff/cnn_graph#1]
When trying to run one of your jupyter notebooks on GPU (`mnist.ipynb` for example), I get the following error when the tensorflow session is started in your model fitting routine:
```
F tensorflow/stream_executor/cuda/cuda_driver.cc:316] current context was not created by the StreamExecutor cuda_driver API: 0x3989db0; a CUDA runtime call was likely performed without using a StreamExecutor context
```

Have you experienced this kind of problem? I think this might be due to importing/running other jupyter notebooks from within the notebook using magic commands like `%run -n models.ipynb`.

**Comment by mdeff** [comment]
I never experienced such issue. Which version of TensorFlow are you using ?

**Comment by tkipf** [comment]
Thanks for your quick response. I am using v0.10.0rc0.

**Comment by mdeff** [comment]
I developed it with 0.8, could your try that ? Maybe something changed in TF such that we have to create this `StreamExecutor`.

**Comment by tkipf** [comment]
Good point, I'll give it a try!

**Comment by tkipf** [comment]
Downgrading to TensorFlow v0.8 solves the `CUDA StreamExecutor` problem. I could not pin down the exact location in the code that throws the error, unfortunately.

I am still facing some issues training a model like the following (using the chebyshev5 filter function):

```
NN architecture
  input: M_0 = 960
  layer 1: cgconv1
    representation: M_1 * F_1 / p_1 = 960 * 32 / 4 = 7680
    weights: F_0 * F_1 * K_1 = 1 * 32 * 25 = 800
    biases: F_1 = 32
  layer 2: cgconv2
    representation: M_2 * F_2 / p_2 = 240 * 64 / 4 = 3840
    weights: F_1 * F_2 * K_2 = 32 * 64 * 25 = 51200
    biases: F_2 = 64
  layer 3: fc1
    representation: M_3 = 512
    weights: M_2 * M_3 = 3840 * 512 = 1966080
    biases: M_3 = 512
  layer 4: logits (softmax)
    representation: M_4 = 10
    weights: M_3 * M_4 = 512 * 10 = 5120
    biases: M_4 = 10
```

After (rather slow) initial 600 training updates (the model is running on a GTX Titan X):

```
step 600 / 11000 (epoch 1.00 / 20):
  learning_rate = 1.90e-02, loss_average = 3.56e+00
  validation accuracy: 97.64 (4882 / 5000), f1 (weighted): 97.64, loss: 3.49e+00
  time: 778s
```

The model training apparently freezes / slows down considerably. Even after one hour wall-clock time the model does not reach training step 1200. Have you experienced similar issues?

**Comment by pklfz** [comment]
@tkipf I faced StreamExecutor problem with tensorflow v0.10.0. I find it is caused by the GPU conflict between gensim (Theano backend) and tensorflow. So I change the Theano config from `device = gpu` to `device = cpu` and solve it.

**Comment by tkipf** [comment]
Excellent, thanks!

**Comment by mdeff** [comment]
Thanks @pklfz ! Strange that this conflict is not problematic for tensorflow 0.8...

**Comment by mdeff** [comment]
BTW gensim is only used to embed words for the 20NEWS experiment. It should not be an issue in most cases. But `utils.py` does indeed import it. (I may refactor that.)

**Comment by pklfz** [comment]
#https://github.com/tensorflow/tensorflow/issues/916
