### ISSUE TITLE
How can I apply this method to a graph that is not built up features but on individual node? 

### ISSUE THREAD

**Issue by LiangGou** [mdeff/cnn_graph#10]
Hi, Michaël

Thanks for the great work and sharing the codes. 

I have node classification problem in a graph where the link is built upon additional information, not on features. For example, in a social network, each node is a person who has a set of features, and their connections are created by their social interaction. I want to classify the node with different social roles. In this case, the graph is not built with the features as you proposed in the paper. I am thinking to use your framework. One approach is to pass the features of all nodes through the Laplacian graph like in this approach: https://github.com/tkipf/gcn. However, this is not going to scale up, since I have to use all data points to do the computation.  I have trouble to figure out how to do this in batch fashion. Do you have any recommendation or suggestions?

Thank you very much!

**Comment by tkipf** [comment]
The setting you describe is still being researched, a Stanford student project seemed to have some success with this approach, though: https://web.stanford.edu/class/cs224n/reports/2758630.pdf

The essential tricks are: creating mini-batches by sampling a set of nodes and a set of their neighbors (very inefficient, but works), and hoping for an inductive bias in your model, so that you can train on some (small) part of the graph and apply the model to the rest of the graph.

**Comment by mdeff** [comment]
Hi, Thanks for your interest. :)

The graph does not have to be constructed from features. It'll work fine as long as you can provide a (weighted) adjacency matrix, wherever it comes from. In my framework, features are seen as signals defined on a graph.

As @tkipf pointed out, minibatching for node classification is still an open problem. If you can afford it, do full batch. If you cannot, try to sample.

**Comment by LiangGou** [comment]
Many thanks to both of you guys, @tkipf @mdeff. This is a fascinating field, and thanks a lot to your contributions!

**Comment by LiangGou** [comment]
One more question, for filter = 'chebyshev5', I looked into the codes, and found that it seems not conduct any chebyshev operation in this function:

def chebyshev5(self, x, L, Fout, K):

But I did see chebyshev operation in chebyshev2 function. 

Did I miss something?

Thx!

**Comment by mdeff** [comment]
Both do the same thing. There are multiple implementations. In general `chebychev5` is the most efficient.

**Comment by swg209** [comment]
@tkipf @mdeff  Hi, how can I apply this method to a fix graph which has 17 nodes, and every node is a 2048 dim feature, how to choose grid_size ? Thx.
