### ISSUE TITLE
error on  "W.setdiag(0)" function 

### ISSUE THREAD

**Issue by anthony123** [mdeff/cnn_graph#12]
The error messages are:

  A = graph.adjacency(dist, idx).astype(np.float32)
  File "lib/graph.py", line 74, in adjacency
    W.setdiag(0)
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 684, in setdiag
    max_index = min(M, N-k, len(values))
TypeError: object of type 'int' has no len()

When I execute the code  from the usage.ipynb, the above error message prompted。
my python version is 2.7.6

**Comment by mdeff** [comment]
It may be an issue with python 2.7, I've never run the code on python 2. Can you try with python 3.x?

**Comment by anthony123** [comment]
OK
