### ISSUE TITLE
Sporadic Errors during Pooling

### ISSUE THREAD

**Issue by mmcdermott** [mdeff/cnn_graph#14]
I've forked the repo, and am attempting to run through the 'usage.ipynb' jupyter notebook, replacing the random data, targets, and graph with some real data, targets, and graph I have. Doing so Makes the following snippet:
```
graphs, perm = coarsening.coarsen(A_sparse, levels=3, self_connections=False)
X_train_perm = coarsening.perm_data(X_train.values, perm)
```
Occasionally error out with a 'index 563 is out of bounds for axis 0 of size 563' error. This happens sporadically for the same inputs.

**Comment by mmcdermott** [comment]
I think this is because my graph was not connected, which I realize now your system is not intended to work with. I'm not totally sure, but that's my running hypothesis at the moment.

**Comment by mdeff** [comment]
I don't think disconnected graphs should be an issue for the coarsening (definitely not for filtering). Hard to tell what's wrong without the data though. I would suggest to insert some `print` statements around the lines where you get the error.

**Comment by TMorville** [comment]
I have similar issues. Have added a data sample at #36.
