### ISSUE TITLE
New dataset

### ISSUE THREAD

**Issue by FaridehF** [mdeff/cnn_graph#19]
Thank you so much for sharing the idea and code.
I have tried to use the code for my own dataset.
but I got this error and I do not know what the problem is.

, line 131, in <module>
    accuracy, loss, t_step = model.fit(X_train, y_train, X_val, y_val)
,  line 117, in fit
    string, accuracy, f1, loss = self.evaluate(val_data, val_labels, sess)
, line 73, in evaluate
    predictions, loss = self.predict(data, labels, sess)
,line 44, in predict
    batch_labels[:end-begin] = labels[begin:end]
ValueError: could not broadcast input array from shape (100,1) into shape (100)

Which 100 here is the number of batches.

**Comment by mdeff** [comment]
Thanks for your interest. Your labels seem to be a 2-dimensional array (with the second dimension being 1), while the code expects a one dimensional array. You should be able to remove this unwanted dimension with `.squeeze()`.
