### ISSUE TITLE
InternalError: cudnn PoolBackward launch failed

### ISSUE THREAD

**Issue by zhoucheng301** [mdeff/cnn_graph#20]
common['p']  cannot be larger than 1, otherwise, InternalError: cudnn PoolBackward launch failed

**Comment by mdeff** [comment]
I've definitely used it with `p > 1`. Maybe it's due to a newer version of TensorFlow or cuDNN? Try to downgrade to TF 1.0 and CUDA 8. Or try to run it on the CPU.

**Comment by zhoucheng301** [comment]
I use TF 1.3. I will try, thanks for your reply.

**Comment by mdeff** [comment]
You're welcome. Let us know if that solves it. :)
