### ISSUE TITLE
Whole graph classification

### ISSUE THREAD

**Issue by mleming** [mdeff/cnn_graph#21]
I am attempting to classify whole correlational graphs using this code (in particular, adapting code from the `usage.ipynb` file. A previous inquiry about this was closed by the person who asked the question, and another time this came up, it was recommended that the user edit the `base_model` and `cgcnn` classes in `lib/models.py`. This is also referred to as "whole graph classification" in `usage.ipynb`.

How would we edit `lib/models.py` to accommodate whole graph classification?

**Comment by mdeff** [comment]
Answered over email

**Comment by enmce** [comment]
Hello, we have same problem, attempting to use your code for graph classification task. Can you please clarify how to use this net on this task?

**Comment by mleming** [comment]
This was the email conversation I had with him:

Me:
> I have been reading closely your paper "Convolutional Neural Networks on Graphs with Fast Localized Spectral Filtering", and I posted an issue on Github. At the moment, I am trying to classify whole functional brain networks (i.e., several thousand NxN correlational matrices with one-to-one correspondence of nodes). Your paper seemed to be quite a promising means of solving this issue, but the code and several discussions on Github indicated that I may have been mistaken in my understanding, and that whole-graph classification was still a problem not completely addressed. If this is a trivial issue, would you be able to let me know how I would be able to solve it, and if not, would you have time for a conversation to bat around ideas?

mdeff:
> The method is indeed suited for whole graph classification. Especially 
> if you have node features along the graph. The code was unfortunately 
> not developed with graph classification in mind, so you'll have to 
> modify it. The idea is to pass a different Laplacian for each sample, 
> instead of a fixed Laplacian for all samples.

Me:
> Yes, that is my question. What part of lib/models.py would be modified to accommodate one Laplacian per sample?

mdeff:
> The chebyshev5 function needs to be adapted to take a list of 
> Laplacians. I would store this list as a big block-diagonal matrix 
> (where each block is a different graph) to train on batches.

**Comment by mleming** [comment]
I personally found the explanation to be unclear, though if I did understand what he was trying to convey, it would be hacky and inviable, just because storing N matrices in a block-diagonal form would take up N^2 space.

**Comment by mdeff** [comment]
Storing the matrices in a block-diagonal format is for batching. You don't have to do it. Anyway it won't take N² space because the matrices are sparse.

**Comment by mdeff** [comment]
In practice I'd recommend using [PyTorch Geometric](https://pytorch-geometric.readthedocs.io) or [Deep Graph Library](https://www.dgl.ai).
