### ISSUE TITLE
Can graph_conv_cheby method be applied to an arbitrary graph ?

### ISSUE THREAD

**Issue by pinkfloyd06** [mdeff/cnn_graph#26]
Hello,

Let me first thank you for your work.

l would like to ask you whether your  `graph_conv_cheby()` can be applied to an arbitrary graph  such as an `irregular graph`  or just on a grid graph ?

Thank you

**Comment by mdeff** [comment]
Yes absolutely. You only need an adjacency matrix which describes your graph.

**Comment by pinkfloyd06** [comment]
@mdeff Thank you for your answer. Hoever l get confused after looking at your experiment on MNIST [https://github.com/mdeff/cnn_graph/blob/master/nips2016/mnist.ipynb](url)

A = grid_graph(28, corners=False)
and the number of edges per vertex is at least 8.

What if l don't have a grid. l deal with irregular graphs where each graph has  N nodes such that : 

each node_i has k_i vertices.

-So the number of vertices varies from node to another either in the same graph or on different graphs
- The number of nodes per graph is variable
