### ISSUE TITLE
error running the code on coarsening

### ISSUE THREAD

**Issue by jdily** [mdeff/cnn_graph#3]
Hi, I am trying to run the sample code on mnist dataset.
(i.e. in the python notebook "mnist")

I have encounter an issue when it runs the following line of code:
`L, perm = coarsen(A, FLAGS.coarsening_levels)`
The error is :
`IndexError: index 783 is out of bounds for axis 0 with size 783`
at line 119 in function "mestis_one_level"
in coarsening.py...

I am wondering if you encounter the same thing?

thx!

**Comment by jdily** [comment]
I just found out that the issue is repeated as the previous close one...
So sorry about that, let me close it first..
BTW, and thx for the new example notebook!

**Comment by mdeff** [comment]
Hi, good that you found #2. I'm making quite a lot of change these days. So pull regularly, especially if you encounter issues.

Glad that the example notebook is useful to you ! :)

**Comment by jdily** [comment]
Hi thx, I will do that! Thx for keep updating the code!
BTW, I do realize that after you update the structure, your "lib" folder seems not having "__init__.py".
I found in the mnist.ipynb that you try to import things from lib:
`from lib import models, graph, coarsening, utils`..
and I will get  a "ImportError: No module named lib" right now

**Comment by mdeff** [comment]
The `__init__.py` should not be necessary. At least I tried with Python 3.5 and 3.4. Are you able to run `usage.ipynb` ? In `mnist.ipynb`, I add the parent directory to the path with `sys.path.insert(0, '..')` so that it finds the `lib` folder.

**Comment by jdily** [comment]
ah, I think the problem is because I used python 2.7 to run the entire codebase....
sry I didn't mentioned that...
I try to add some additional support for python 2.x in my fork, and it works!

**Comment by mdeff** [comment]
Good that you found out how to support Python 2.7 ! I don't use Python 2.7, so I'm unable to detect errors on that version. Sorry about that. Is  `time.process_time()` the sole problem ?

**Comment by jdily** [comment]
Yeah, for now the process_time is the sole problem I encounter. 
So I just use a simple if to go different functions.. 
It's not a problem in the core function so it's easy to fix.

**Comment by mdeff** [comment]
Good. I'm closing this for now as I'm not going to support Python 2.7. If people are interested in maintaining 2.7 compatibility I'll accept pull requests.

**Comment by rrns10** [comment]
Hii..


I found in the mnist.ipynb that you try to import things from lib: from lib import models, graph, coarsening, utils. and I will get a "ImportError: No module named lib" right now and I am using google colab to run this code.
How can I remove this error while using google colab?
please reply
