### ISSUE TITLE
Implementation for multi-gpu usage

### ISSUE THREAD

**Issue by zhangyu2ustc** [mdeff/cnn_graph#38]
Hi,
  First of all, Thanks a lot for sharing this package.
  I notice that the current package only a single GPU during model training. Is it possible to distribute the training process to multi-gpu, which will accelerate the training process?

Thanks again.
Best,
   Yu.

**Comment by mdeff** [comment]
Thanks for your interest. That's definitely possible but requires the code to be modified. This repo won't be updated as it's purpose is to reproduce the paper.
