### ISSUE TITLE
node regression

### ISSUE THREAD

**Issue by jdily** [mdeff/cnn_graph#4]
Hi, i am experimenting some of my own data, and I think it is relevant to your description about "node regression" setting, but I am not so sure.

So as I understand, (correct me if I am wrong.), take mnist experiment as example, 
Each sample feed into the network is a digit image, conveted to a graph with 28x28 nodes.
The goal is to classify this **entire graph** to a label, say, 8.

What I am looking for is that, I have my own data which is a bigger graph, and there is a value or a vector of values on each node.
And i am thinking if it's possible to:

1.  given a node, only feed in it's neighbors into network
2. the corresponding output of this node input is it's associate value.
I think it is more like I want to use a subgraph as training....

I am not so sure if this is the same as you mentioned in the usage.ipynb node classification/regression..
Do you have any hint or suggestion of how to do that?

Thx in advance~!

**Comment by mdeff** [comment]
The task for MNIST is not to classify a graph (the 28x28 nodes grid is the same for all images) but to classify a **graph signal**. In this context the graph signal is the pixel values. The graph is structuring the pixels, i.e. defining pairwise relationships between them, and is fixed.

Your usage definitely fits in the node classification/regression regime. The code would however have to be adapted, I have nothing fully ready for this usage yet. Please contact me at michael.defferrard@epfl.ch if you're interested in doing that.

**Comment by jdily** [comment]
Hi thx, let me send a mail to you! :)

**Comment by xu-wang11** [comment]
@jdily Hi, I have the same question as you, do you have any progress yet? Maybe you could give me some help~
