### ISSUE TITLE
Name 't' is not defined

### ISSUE THREAD

**Issue by ilteralp** [mdeff/cnn_graph#46]
I have been trying to run `usage.ipynb` notebook. Second cell of the notebook gives `name 't' is not defined` error at line `t = np.tanh(t)`. I guess it should be `t = np.tanh(w)`, Is that right ?

**Comment by mdeff** [comment]
Nope, `t` is defined on the line above, as `t = X.dot(w) + np.random.normal(0, .001, n)`.
